"use client";

import { MapPin, Mail, Phone, Globe, ExternalLink } from "lucide-react";

interface ResumePreviewProps {
    data: any; // The JSON payload generated by the AI parser/matcher
}

export default function ResumePreview({ data }: ResumePreviewProps) {
    if (!data) return <div className="p-8 text-center text-text-muted">No resume data available.</div>;

    const {
        title = "",
        summary = "",
        workHistory = [],
        education = [],
        skills = [],
        projects = []
    } = data;

    return (
        <div className="bg-white text-gray-900 mx-auto bg-white/100 p-8 sm:p-12 shadow-2xl rounded-sm print:shadow-none print:p-0"
            style={{ maxWidth: "850px", minHeight: "1100px" }}>

            {/* ── Header ──────────────────────────────────────────────────────── */}
            <header className="border-b-2 border-gray-900 pb-6 mb-6">
                {/* Fallback Name (Normally we'd pull from User Profile, assuming John Doe for now if missing) */}
                <h1 className="text-4xl font-extrabold tracking-tight uppercase text-gray-900 mb-1">
                    {data.name || "Vardhan"}
                </h1>

                {title && (
                    <h2 className="text-xl font-medium text-gray-700 uppercase tracking-widest mb-4">
                        {title}
                    </h2>
                )}

                <div className="flex flex-wrap gap-4 text-sm text-gray-600">
                    <div className="flex items-center gap-1.5">
                        <Mail className="w-4 h-4" />
                        <span>contact@vardhan.example.com</span>
                    </div>
                    {/* Add more static contact info or pull from db user later */}
                </div>
            </header>

            {/* ── Summary ─────────────────────────────────────────────────────── */}
            {summary && (
                <section className="mb-6">
                    <p className="text-sm leading-relaxed text-gray-800">
                        {summary}
                    </p>
                </section>
            )}

            {/* ── Experience ──────────────────────────────────────────────────── */}
            {workHistory && workHistory.length > 0 && (
                <section className="mb-6">
                    <h3 className="text-sm font-bold uppercase tracking-widest text-gray-900 border-b border-gray-300 pb-1 mb-4">
                        Experience
                    </h3>
                    <div className="space-y-5">
                        {workHistory.map((job: any, index: number) => (
                            <div key={index}>
                                <div className="flex justify-between items-start mb-1">
                                    <h4 className="font-bold text-gray-900 text-sm">
                                        {job.role}
                                    </h4>
                                    <span className="text-xs font-semibold text-gray-600 whitespace-nowrap ml-4">
                                        {job.date}
                                    </span>
                                </div>
                                <div className="text-sm italic text-gray-700 mb-2">
                                    {job.company}
                                </div>

                                {job.description && (
                                    <ul className="list-disc list-outside ml-4 space-y-1.5 text-sm text-gray-800">
                                        {job.description.split('\n').filter((p: string) => p.trim() !== '').map((point: string, i: number) => (
                                            <li key={i} className="leading-relaxed pl-1">{point.trim().replace(/^[-•]\s*/, '')}</li>
                                        ))}
                                    </ul>
                                )}
                            </div>
                        ))}
                    </div>
                </section>
            )}

            {/* ── Projects ────────────────────────────────────────────────────── */}
            {projects && projects.length > 0 && (
                <section className="mb-6">
                    <h3 className="text-sm font-bold uppercase tracking-widest text-gray-900 border-b border-gray-300 pb-1 mb-4">
                        Projects
                    </h3>
                    <div className="space-y-4">
                        {projects.map((project: any, index: number) => (
                            <div key={index}>
                                <h4 className="font-bold text-gray-900 text-sm mb-1">
                                    {project.name}
                                </h4>
                                {project.description && (
                                    <p className="text-sm leading-relaxed text-gray-800">
                                        {project.description}
                                    </p>
                                )}
                            </div>
                        ))}
                    </div>
                </section>
            )}

            <div className="grid grid-cols-2 gap-8">
                {/* ── Skills ──────────────────────────────────────────────────── */}
                {skills && skills.length > 0 && (
                    <section>
                        <h3 className="text-sm font-bold uppercase tracking-widest text-gray-900 border-b border-gray-300 pb-1 mb-3">
                            Skills
                        </h3>
                        <div className="flex flex-wrap gap-2 text-sm text-gray-800">
                            {skills.map((skill: string, index: number) => (
                                <span key={index} className="bg-gray-100 px-2.5 py-1 rounded font-medium">
                                    {skill}
                                </span>
                            ))}
                        </div>
                    </section>
                )}

                {/* ── Education ───────────────────────────────────────────────── */}
                {education && education.length > 0 && (
                    <section>
                        <h3 className="text-sm font-bold uppercase tracking-widest text-gray-900 border-b border-gray-300 pb-1 mb-3">
                            Education
                        </h3>
                        <div className="space-y-3">
                            {education.map((edu: any, index: number) => (
                                <div key={index} className="text-sm text-gray-800">
                                    <h4 className="font-bold text-gray-900">{edu.degree}</h4>
                                    <p>{edu.school}</p>
                                    <p className="text-xs text-gray-500 mt-0.5">{edu.date}</p>
                                </div>
                            ))}
                        </div>
                    </section>
                )}
            </div>

        </div>
    );
}
